#!/bin/bash

# === [Start] Auto-generated by user request ===
cd /home/ubuntu/OpenSfM/
# === [Start] End ===

# Exit immediately on error
set -e

echo "[INFO] Running run.sh with argument: $1"

# === [1] 檢查參數 ===
if [ "$#" -ne 1 ]; then
    echo "[ERROR] Usage: ./run.sh /path/to/image/folder"
    exit 1
fi

INPUT_PATH="$1"

if [ ! -d "$INPUT_PATH" ]; then
    echo "[ERROR] Provided path is not a directory: $INPUT_PATH"
    exit 1
fi

# === [2] 檢查是否有圖片 ===
FIRST_IMAGE=$(ls "$INPUT_PATH" | grep -iE '\.jpg|\.jpeg|\.png' | head -n 1)
if [ -z "$FIRST_IMAGE" ]; then
    echo "[ERROR] No image files (.jpg, .jpeg, .png) found in $INPUT_PATH"
    exit 1
fi

# === [3] 檢查 opensfm_run_all 的執行權限 ===
OSFM_SCRIPT="/home/ubuntu/OpenSfM/bin/opensfm_run_all"
echo "[INFO] File type of opensfm_run_all:"
file "$OSFM_SCRIPT"

if [ ! -x "$OSFM_SCRIPT" ]; then
    echo "[INFO] Granting execute permission to opensfm_run_all..."
    chmod +x "$OSFM_SCRIPT"
fi

# === [4] 啟用 Conda 環境 ===
echo "[INFO] Activating Conda environment..."
__conda_setup="$('/home/ubuntu/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    export PATH="/home/ubuntu/miniconda3/bin:$PATH"
fi

conda activate SFM

# === [5] 建立目標資料夾 & 複製圖片 ===
FOLDER_NAME="${FIRST_IMAGE%.*}"
TARGET_DIR="/home/ubuntu/OpenSfM/data/${FOLDER_NAME}/images"

echo "[INFO] Copying images to: $TARGET_DIR"
mkdir -p "$TARGET_DIR"
cp "$INPUT_PATH"/* "$TARGET_DIR"

# === [6] 執行 OpenSfM 主流程 ===
echo "[INFO] Running OpenSfM pipeline on folder: $FOLDER_NAME"
# 設定 PYTHONPATH 確保 Python 可以找到 opensfm 模組
export PYTHONPATH=/home/ubuntu/OpenSfM
# 嘗試切換到 OpenSfM 根目錄
cd /home/ubuntu/OpenSfM || {
    echo "[ERROR] Failed to cd to /home/ubuntu/OpenSfM"
    exit 1
}
echo "[INFO] Running before"
bash bin/opensfm_run_all "data/${FOLDER_NAME}"


# === [7] 執行後處理 Python 腳本 ===
PLY_PATH="data/${FOLDER_NAME}/undistorted/depthmaps/merged.ply"

if [ ! -f "$PLY_PATH" ]; then
    echo "[ERROR] PLY file not found: $PLY_PATH"
    exit 1
fi

echo "[INFO] Running callFilename.py on: $PLY_PATH"
python3 data/callFilename_pop.py "$PLY_PATH"

# === [8] 結束 ===
echo "[INFO] Pipeline completed successfully."
conda deactivate

# === [End] Auto-return to backend ===
cd /home/ubuntu/backend/
# === [End] ===
